### ISSUE TITLE
Change the license to MIT (or Apache 2.0)

### ISSUE THREAD

**Issue by rubyconvict** [panter/seed_box#3]
First of all, I think that this gem is a nice and tiny helper for MIT-licensed Rails, a useful piece of code, but I have some issues with the LGPL license used.

I would like to use the gem in my commercial projects, without disclosing source code or multi-licensing, without modification or with modification, if I need it. I don't have any copyright lawyers around me though and I'm not willing to take any risks.

Is it completely out of question to change the license?

**Comment by koffeinfrei** [comment]
My understanding is that the LGPL allows the usage of gems in differently licensed projects (including commercial). There's no official statement from the FSF regarding Ruby, but they have an article [The LGPL and Java](http://www.gnu.org/licenses/lgpl-java.html) which should translate to Ruby too.

> the LGPL works as intended with all known programming languages, including Java. Applications which link to LGPL libraries need not be released under the LGPL. Applications need only follow the requirements in section 6 of the LGPL: allow new versions of the library to be linked with the application; and allow reverse engineering to debug this.

In summary you should be able to use that library without any legal repercussions. But I'm not a lawyer. By creating this library my intention was exactly that, namely to allow the use in any Rails project. Otherwise I would have licensed it under the GPL.

While I'm the creator of this library I'm technically not the copyright holder, which is the company "Panter" where I worked when I created this gem. So technically I'm not allowed to change the license without permission of the company (because I don't work there anymore).

If you still have doubts, @panterch would very likely not be against changing the license.

**Comment by macrozone** [comment]
> My understanding is that the LGPL allows the usage of gems in differently licensed projects (including commercial). There's no official statement from the FSF regarding Ruby, but they have an article [The LGPL and Java](http://www.gnu.org/licenses/lgpl-java.html) which should translate to Ruby too.
> 
> > the LGPL works as intended with all known programming languages, including Java. Applications which link to LGPL libraries need not be released under the LGPL. Applications need only follow the requirements in section 6 of the LGPL: allow new versions of the library to be linked with the application; and allow reverse engineering to debug this.
> 
> In summary you should be able to use that library without any legal repercussions. But I'm not a lawyer. By creating this library my intention was exactly that, namely to allow the use in any Rails project. Otherwise I would have licensed it under the GPL.
> 


i think @rubyconvict referred to this summary that github shows:

<img width="280" alt="Bildschirmfoto 2022-01-13 um 12 45 28" src="https://user-images.githubusercontent.com/1972353/149324696-9f09c691-02f0-40ca-b532-1a9be5b1823d.png">

i am also not a lawyer so i understand the devlopers desire for simpler licence conditions ;-)

> While I'm the creator of this library I'm technically not the copyright holder, which is the company "Panter" where I worked when I created this gem. So technically I'm not allowed to change the license without permission of the company (because I don't work there anymore).
> 
> If you still have doubts, @panterch would very likely not be against changing the license.

that was also my understanding when i read the issue ;-) 

We as panter hereby agree that you change the licence to MIT :-)

**Comment by koffeinfrei** [comment]
> We as panter hereby agree that you change the licence to MIT :-)

Lovely :smile_cat: 

PR created https://github.com/panter/seed_box/pull/4

**Comment by jeredepp** [comment]
![TheGloriousTaleOfBayeux (6)](https://user-images.githubusercontent.com/5755315/149333414-b87015f7-aad0-467b-85de-38995cfb669e.png)

**Comment by koffeinfrei** [comment]
Version 0.4.0 with the MIT license relased: https://rubygems.org/gems/seed_box/versions/0.4.0

**Comment by rubyconvict** [comment]
Awesome! Thank you! 🎉
